config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses
  resources :students do 
    resources :addresses
  end 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :students
end 

app/models/student.rb
class Student < ApplicationRecord 
  has_many :addresses
  has_and_belongs_to_many :courses
end 

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController 
  def new 
    @student = Student.find(params[:student_id])
    @address = @student.addresses.new
  end 

  def create
    @student = Student.find(params[:student_id])
    @address = @student.addresses.create(address_params)

    redirect_to student_path(@student)
  end 

    private 

      def address_params 
        params.require(:address).permit(:description, :street, :city, :state, :zipcode)
      end 

    
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ActionController::Base
  def show
    @course = Course.find(params[:id])
  end 
end 

app/controllers/students_controller.rb
class StudentsController < ApplicationController 
  def new 
    @student = Student.new 
  end 

  def index
    @students = Student.all
  end 

  def show 
    @student = Student.find(params[:id])
  end 

  def create 
    @student = Student.create(student_params)

    redirect_to student_path(@student)
  end

  def destroy 
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end 

  def edit 
    @student = Student.find(params[:id])
  end 

  def update 
    @student = Student.find(params[:id])
    @student.update(student_params)

    redirect_to student_path(@student)
  end 

    private

    def student_params
      params.require(:student).permit(:name)
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>Fill in the address for <%=@student.name %></h1>

<%=form_for [@student, @address] do |f| %> 

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <%= f.submit %>
<%end%>

app/views/courses/show.html.erb
<h1>Course name: <%= @course.title %></h1>

<h6>Students enrolled in this course</h6>

<% @course.students.each do |student| %>
  <p><%= student.name %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit your student below</h1>

<%= form_for(@student) do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.submit%>

<%end%>

app/views/students/index.html.erb
<h1>View list of all students</h1>

<%= link_to "Create new student", new_student_path %>

<% @students.each do |student| %>
  <p><%= link_to student.name,student_path(student)  %> <%= link_to "Delete", student_path(student), method: :delete %></p>
<% end %>

app/views/students/new.html.erb
<h1>Create a new student</h1>

<%= form_for(@student) do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.submit%>

<%end%>

app/views/students/show.html.erb
<%= link_to "Create new student", new_student_path %>
<%= link_to "Browse all students", students_path %>
<h1>Showing details for a particular student<h1>


<%= @student.name %>

<h1>All address details below</h1>

<% @student.addresses.each do |detail| %>
  <p>Description :<%= detail.description %></p>
  <p>Street: <%= detail.street %></p>
  <p>City: <%= detail.city %></p>
  <p>State: <%= detail.state %></p>
  <p>Zipcode: <%= detail.zipcode %></p>
  <p>---------------------------------------------</p>
<%end %>

<h1>Courses this student is taking</h1>

<% @student.courses.each do |course |%>
  <p><%= course.title %></p>
<% end %>